### ISSUE TITLE
Rename check UnorderedKeys to UnorderedKey

### ISSUE THREAD

**Issue by mgrachev** [mgrachev/dotenv-linter#117]
All checks should have names in a single form.
So need to rename the check `UnorderedKeys` to `UnorderedKey`.

**Comment by pineapplethief** [comment]
I'll try to do it in the weekend

**Comment by VishvajitP** [comment]
@mgrachev Can I take it ?

**Comment by mgrachev** [comment]
@VishvajitP Sorry, but not, because @pineapplethief is already doing it.
