### ISSUE TITLE
IncorrectDelimiter: Show check name in message

### ISSUE THREAD

**Issue by mgrachev** [mgrachev/dotenv-linter#121]
Right now the message looks like this:
```
.env:2 The FOO-BAR key has incorrect delimiter
```

Need to add the check name to the message:
```
.env:2 IncorrectDelimiter: The FOO-BAR key has incorrect delimiter
```

**Comment by undef1nd** [comment]
I guess it's similar to #123 , isn't it?  I'd take this one as well in such a case.

**Comment by mstruebing** [comment]
It definitely is, go for it :tada:

**Comment by undef1nd** [comment]
@mstruebing Cool. Plz, assign both to me. Thanks!
