### ISSUE TITLE
LeadingCharacter: Show check name in message

### ISSUE THREAD

**Issue by mgrachev** [mgrachev/dotenv-linter#123]
Right now the message looks like this:
```
.env:2 Invalid leading character detected
```

Need to add the check name to the message:
```
.env:2 LeadingCharacter: Invalid leading character detected
```

**Comment by undef1nd** [comment]
Heya, I can give it a try :-)

**Comment by michaetto** [comment]
How about this: https://github.com/mgrachev/dotenv-linter/pull/141 ?
Not sure why to make reallocations for static strings.
I think other checker can be changed this way as well.
Also maybe cloning will not be needed if Warning type etc. are also borrowed with proper lifetimes,  make reallocation when it is actually needed (most likely in replace scenarios etc.)

**Comment by michaetto** [comment]
@undef1nd do not hesitate to proceed with your solution, I've just only wanted to raise the topic of unnecessary reallocation with #141 as an example

**Comment by undef1nd** [comment]
@michaetto But yours actually solves the problem, right? I don't have any objections against it being merged :-)

**Comment by mgrachev** [comment]
@michaetto Thank you for raising the topic of unnecessary reallocations. I totally agree with you.
If you know how to optimize mu code - let me know 😃 Any help appreciated! 🙏

As I can see - you have done this issue, so I will assign this issue to you if you don't mind.

**Comment by mgrachev** [comment]
@undef1nd Sure!

**Comment by michaetto** [comment]
All right then :+1: , you have it here: #144
