### ISSUE TITLE
Add test coverage for --exclude argument

### ISSUE THREAD

**Issue by mgrachev** [mgrachev/dotenv-linter#127]
Example: https://github.com/mgrachev/dotenv-linter/blob/master/tests/cli_test.rs

**Comment by sonro** [comment]
I'll jump in on this one.

**Comment by sonro** [comment]
Also, while looking at [cli_test.rs](https://github.com/mgrachev/dotenv-linter/blob/master/tests/cli_test.rs), I noticed a lot of the tests could be refactored using a helper function. Shall I implement that as well?

**Comment by mgrachev** [comment]
@sonro Yes, it would be just great!

**Comment by mgrachev** [comment]
You can also split the `cli_test.rs` file into several smaller ones files.
