### ISSUE TITLE
Remove inline comments from lines

### ISSUE THREAD

**Issue by artem-russkikh** [mgrachev/dotenv-linter#38]
We should remove inline comments before running checks, because inline comments may affect checks behaviour.

Example:
```env
FOO=BAR # some comment ===
```

Is need to ensure that commented lines with leading spaces will be skipped too:

```env
 # FOO=BAR
```

**Comment by mgrachev** [comment]
> Is need to ensure that commented lines with leading spaces will be skipped too:
> 
> ```
>  # FOO=BAR
> ```

Moved to the issue https://github.com/mgrachev/dotenv-linter/issues/39

**Comment by mstruebing** [comment]
Whoever will work on that issue, please keep in mind some edge cases, here I created a complex password and tested it in different situations:

```
$ FOO=ohroothoo[d6mahl4eech3ied@ee#sh4ahng,e6eic0os$ahSh4feng9oo6duc6i
$ echo $FOO
ohroothoo[d6mahl4eech3ied@ee#sh4ahng,e6eic0os

$ FOO=ohroothoo[d6mahl4eech3ied@ee #sh4ahng,e6eic0os$ahSh4feng9oo6duc6i
$ echo $FOO
ohroothoo[d6mahl4eech3ied@ee

$ FOO='ohroothoo[d6mahl4eech3ied@ee #sh4ahng,e6eic0os$ahSh4feng9oo6duc6i'
$ echo $FOO
ohroothoo[d6mahl4eech3ied@ee #sh4ahng,e6eic0os$ahSh4feng9oo6duc6i
```

**Comment by mgrachev** [comment]
Guys, I thought about it and don't fully understand how inline comments can affects to the behaviour of checks, because we don't check values.

**Comment by mstruebing** [comment]
I think you are right.
I currently see no need to check that.

**Comment by mgrachev** [comment]
@mstruebing Thank you. I close this issue.
