### ISSUE TITLE
Add check: Duplicated keys

### ISSUE THREAD

**Issue by mgrachev** [mgrachev/dotenv-linter#5]
Example:

```env
# .env

# Wrong
RAILS_ENV=development
RAILS_ENV=test

# Correct
RAILS_ENV=development
RAILS_MAX_THREADS=5
```

This check should display a message:
> .env:2 The RAILS_ENV key is duplicated

**Comment by quicktour** [comment]
I'll take these issue

**Comment by mstruebing** [comment]
@quicktour any news on that or are you stuck? Otherwise I would love to try it.
