### ISSUE TITLE
Fix a bug with duplicate paths

### ISSUE THREAD

**Issue by mgrachev** [mgrachev/dotenv-linter#57]
We can pass an argument to `dotenv-linter` to include some files to check:

```bash
$ dotenv-linter -i .my-env-file
.env:1 Leading space detected
.my-env-file:1 Leading space detected
```

If the file already exists in the paths, we will get a duplicate result:

```bash
$ dotenv-linter -i .env -i .env
.env:1 Leading space detected
.env:1 Leading space detected
.env:1 Leading space detected
```

Need to fix that and write tests for that case.

Link: https://github.com/mgrachev/dotenv-linter/blob/master/src/lib.rs#L101

**Comment by Louis-Lesage** [comment]
Where should I put the test. Should I create a tests folder or should I write it next to the implementation of the tested function?

**Comment by mgrachev** [comment]
I think you should write integration tests for that case and create the `tests` folder.
